backend:
  name: github
  repo: leandrocfe/filamentphp.test
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "plugins"
    label: "Plugins"
    folder: "content/plugins"
    create: true
    slug: "{{fields.author_slug}}-{{fields.slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - { label: "Plugin Name", name: "name", widget: "string", required: true }

      - { label: "Slug", name: "slug", widget: "string", required: true, pattern: [ "^[a-z0-9-]+$", "Use apenas letras minúsculas, números e hífens." ] }

      - { label: "Author Slug", name: "author_slug", widget: "string", required: true }

      - label: "Categories"
        name: "categories"
        widget: "select"
        multiple: true
        required: true
        options:
          - form-builder
          - form-field
          - spatie
          - table-builder
          - table-column

      - label: "Description"
        name: "description"
        widget: "text"
        required: true
        min_length: 20
        max_length: 300

      - label: "Discord URL"
        name: "discord_url"
        widget: "hidden"

      - label: "Docs URL"
        name: "docs_url"
        widget: "string"
        required: false
        hint: "If you have multiple documentation URLs, please use the 'Docs URLs' field instead."

      - label: "Docs URLs"
        name: "docs_urls"
        widget: "object"
        required: false
        hint: "If you have multiple documentation URLs, please use this field."
        fields:
          - label: "v2"
            name: "v2"
            widget: "string"
          - label: "v3"
            name: "v3"
            widget: "string"
          - label: "v4"
            name: "v4"
            widget: "string"

      - { label: "GitHub Repository", name: "github_repository", widget: "string", required: true }

      - { label: "Has Dark Theme?", name: "has_dark_theme", widget: "boolean", default: false }

      - { label: "Has Translations?", name: "has_translations", widget: "boolean", default: false }

      - label: "Supported Versions"
        name: "versions"
        widget: "select"
        multiple: true
        required: true
        options:
          - v2
          - v3
          - v4

      - { label: "Publish Date", name: "publish_date", widget: "datetime", format: "YYYY-MM-DD", default: "" }